#!/usr/bin/env sh
set -eu

DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
cd "$DIR"

exec "$DIR/build/psi" \
  -r 2 \
  -sf "$DIR/data/processed/veriwild_server.bin" \
  -rf "$DIR/data/processed/veriwild_client.bin" \
  -dataset VERI-Wild \
  -ei 64 \
  -cf batchpir
